# Refresh your Numpy Knowledge

### NumPy Arrays
- NumPy array are by default Homogeneous meaning data inside an array must be of the same Datatype.
- NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and many more.
- This set of exercises adaped and added for my students
> by Callou


Import Numpy:

In [1]:
import numpy as np

What is the version of NumPy being used?

In [2]:
print(np.__version__)

2.0.2


Create a NumPy array with 3 elements, and all the elements are 0.0.

In [3]:
np.zeros(3)

array([0., 0., 0.])

What is the data type of the output of the output of code above?

In [4]:
type(np.zeros(3))

numpy.ndarray

How would you create a 3x2 array of zeros?

In [5]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

How would you create a 3x2x2 array of zeros?

In [8]:
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

What is the shape of the array created by `np.zeros(3)`?

In [9]:
np.zeros(3).shape

(3,)

What is the shape of the 3x2 array of zeros?

In [10]:
np.zeros((3,2)).shape

(3, 2)

How to check the number of dimensions of `np.zeros(7)`?

In [11]:
np.zeros(7).ndim

1

What is the number of dimensions of the 3x2 array of zeros?

In [12]:
np.zeros((3,2)).ndim

2

How would you create a 2x3 array of ones?

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

How would you create a NumPy array from a list of lists?

In [14]:
np.array([[1,2,3,4],[10,20,30,40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

How would you create a NumPy array with a range of values from 0 up to (but not including) 5?

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

How would you create a NumPy array with a range of values from 0 up to (but not including) 5, with a step of 0.5?

In [16]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

How would you create a NumPy array with 10 evenly spaced values between 0 and 4.5 (inclusive)?

In [17]:
np.linspace(0,4.5,10)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

How would you create two NumPy arrays of random numbers with a million elements each?

In [18]:
n= 1000000
a = np.random.rand(n)
b = np.random.rand(n)

What does this code define?

In [19]:
import time

class Timer:
    def __init__(self):
        self.times = []

    def start(self):
        self.tik = time.time()

    def stop(self):
        self.times.append(time.time() - self.tik)
        return self.times[-1]

How is the `Timer` class used to measure the time taken for element-wise addition using a loop and using NumPy's vectorized addition?

In [21]:
timer = Timer()

timer.start()
c = np.zeros(n)
for i in range(n):
    c[i] = a[i] + b[i]
timer.stop()

0.8528001308441162

In [22]:
timer.start()
c = a + b
timer.stop()

0.0059392452239990234

What are the recorded times for the two addition methods?

In [23]:
timer.times

[0.8528001308441162, 0.0059392452239990234]

What is the speedup of the NumPy vectorized addition compared to the loop?

In [24]:
print("speedup is: %s" % (timer.times[0]/timer.times[1]))

speedup is: 143.5872907550881


How is a 2x4 NumPy array created and printed?

In [25]:
a = np.array([[1,2,3,4],[10,20,30,40]])
print(a)

[[ 1  2  3  4]
 [10 20 30 40]]


How is the 2x4 array reshaped into a 4x2 array and printed?

In [26]:
b = a.reshape(4,2)
print(b)

[[ 1  2]
 [ 3  4]
 [10 20]
 [30 40]]


How is the element at the first row and second column (index [0,1]) of the reshaped array `b` changed to -1?

In [27]:
b[0,1] = -1

What is the content of array `b` after the modification?

In [28]:
print(b)

[[ 1 -1]
 [ 3  4]
 [10 20]
 [30 40]]


What is the content of array `a` after modifying `b`? (Note: Reshaping creates a view, so changes in `b` affect `a`).

In [29]:
print(a)

[[ 1 -1  3  4]
 [10 20 30 40]]


How is a NumPy array `c` created with values from 3 to 9?

In [30]:
c = np.array([3,4,5,6,7,8,9])

How would you get a boolean array indicating which elements in array `c` are greater than 6?

In [31]:
c > 6

array([False, False, False, False,  True,  True,  True])

How would you select the elements from array `c` that are greater than 6 using boolean indexing?

In [32]:
c[c>6]

array([7, 8, 9])